<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" 
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Super Kings | Academy Administration</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Outfit:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
  <link rel="stylesheet" href="css/style.css" />
</head>
<body>
  <aside class="sidebar" id="sidebar">
    <a class="brand" href="#dashboard"><span class="brand-mark"><i class="fa-solid fa-shuttlecock"></i></span><span>SUPER KINGS<small>BADMINTON ACADEMY</small></span></a>
    <p class="menu-label">MAIN MENU</p>
    <nav>
      <a class="nav-link active" data-page="dashboard" href="#dashboard"><i class="fa-solid fa-grid-2"></i>Dashboard</a>
      <a class="nav-link" data-page="members" href="#members"><i class="fa-solid fa-users"></i>Members <span class="nav-count">128</span></a>
      <a class="nav-link" data-page="batches" href="#batches"><i class="fa-regular fa-clock"></i>Batches & Timings</a>
      <a class="nav-link" data-page="courts" href="#courts"><i class="fa-solid fa-table-cells-large"></i>Courts</a>
      <a class="nav-link" data-page="payments" href="#payments"><i class="fa-solid fa-wallet"></i>Fees & Payments</a>
      <a class="nav-link" data-page="schedule" href="#schedule"><i class="fa-regular fa-calendar-days"></i>Schedule</a>
      <a class="nav-link" data-page="reports" href="#reports"><i class="fa-solid fa-chart-pie"></i>Reports</a>
    </nav>
    <p class="menu-label secondary">MANAGEMENT</p>
    <nav>
      <a class="nav-link" data-page="data" href="#data"><i class="fa-solid fa-file-excel"></i>Excel / Data</a>
      <a class="nav-link" data-page="settings" href="#settings"><i class="fa-solid fa-gear"></i>Settings</a>
    </nav>
    <div class="sidebar-foot"><div class="help-icon"><i class="fa-regular fa-circle-question"></i></div><div><b>Need help?</b><small>Contact academy support</small></div></div>
  </aside>

  <main class="main-content">
    <header class="topbar">
      <button class="mobile-menu" id="menuToggle"><i class="fa-solid fa-bars"></i></button>
      <div class="crumb"><span id="pageEyebrow">Overview</span><h1 id="pageTitle">Good morning, Admin <span>👋</span></h1></div>
      <div class="header-actions"><button class="icon-button"><i class="fa-regular fa-bell"></i><span class="notify"></span></button><div class="date-chip"><i class="fa-regular fa-calendar"></i><span>July 30, 2026</span></div><div class="admin-avatar">SK</div></div>
    </header>

    <section class="page active" id="dashboard">
      <div class="hero-row"><div><p class="muted">Here's what's happening at your academy today.</p></div><button class="primary-btn" data-modal="memberModal"><i class="fa-solid fa-plus"></i>Add new member</button></div>
      <div class="stats-grid">
        <article class="stat-card"><div class="stat-icon blue"><i class="fa-solid fa-users"></i></div><div><p>Total Members</p><h2>128</h2><span class="up"><i class="fa-solid fa-arrow-trend-up"></i> 8.5% <em>vs last month</em></span></div></article>
        <article class="stat-card"><div class="stat-icon mint"><i class="fa-solid fa-user-check"></i></div><div><p>Active Members</p><h2>116</h2><span class="up"><i class="fa-solid fa-arrow-trend-up"></i> 4.2% <em>vs last month</em></span></div></article>
        <article class="stat-card"><div class="stat-icon orange"><i class="fa-solid fa-indian-rupee-sign"></i></div><div><p>July Collections</p><h2>₹1,08,500</h2><span class="up"><i class="fa-solid fa-arrow-trend-up"></i> 12.3% <em>vs last month</em></span></div></article>
        <article class="stat-card"><div class="stat-icon rose"><i class="fa-regular fa-clock"></i></div><div><p>Pending Fees</p><h2>₹18,400</h2><span class="down"><i class="fa-solid fa-arrow-trend-down"></i> 6 members <em>awaiting payment</em></span></div></article>
      </div>
      <div class="dashboard-grid">
        <article class="panel collection-panel"><div class="panel-head"><div><h3>Monthly collections</h3><p>Fee collection performance</p></div><select><option>Last 6 months</option></select></div><div class="chart-wrap"><div class="chart-y"><span>₹1.2L</span><span>₹90K</span><span>₹60K</span><span>₹30K</span><span>₹0</span></div><div class="bar-chart"><div class="bar-group"><i style="height:55%"></i><span>Feb</span></div><div class="bar-group"><i style="height:66%"></i><span>Mar</span></div><div class="bar-group"><i style="height:60%"></i><span>Apr</span></div><div class="bar-group"><i style="height:77%"></i><span>May</span></div><div class="bar-group"><i style="height:72%"></i><span>Jun</span></div><div class="bar-group current"><b>₹1.08L</b><i style="height:91%"></i><span>Jul</span></div></div></div><div class="chart-total"><span>Total collected</span><strong>₹5,32,800</strong><small><i class="fa-solid fa-arrow-trend-up"></i> 9.8% growth</small></div></article>
        <article class="panel payments-panel"><div class="panel-head"><div><h3>Pending payments</h3><p>Members who haven't cleared July fees</p></div><a href="#payments" class="text-link">View all <i class="fa-solid fa-arrow-right"></i></a></div><div class="pending-list"><div><span class="avatar purple">RP</span><p><b>Rahul Prakash</b><small>Morning Elite · Left Court</small></p><strong>₹1,500</strong></div><div><span class="avatar coral">AN</span><p><b>Ananya Nair</b><small>Evening Smash · Right Court</small></p><strong>₹1,800</strong></div><div><span class="avatar amber">VS</span><p><b>Vikram Shah</b><small>Morning Elite · Left Court</small></p><strong>₹1,500</strong></div><div><span class="avatar blue-avatar">SM</span><p><b>Sneha Menon</b><small>Weekend Warriors · Right Court</small></p><strong>₹1,800</strong></div></div></article>
      </div>
      <div class="dashboard-grid lower-grid">
        <article class="panel"><div class="panel-head"><div><h3>Today's batches</h3><p>Wednesday, July 30</p></div><a href="#schedule" class="text-link">Full schedule <i class="fa-solid fa-arrow-right"></i></a></div><div class="today-batches"><div><span class="time">06:00<small>AM</small></span><i class="line-dot"></i><p><b>Morning Elite</b><small>Left Court · 10/12 members</small></p><span class="status partial">2 slots left</span></div><div><span class="time">07:00<small>AM</small></span><i class="line-dot"></i><p><b>Morning Rally</b><small>Right Court · 12/12 members</small></p><span class="status full">Full</span></div><div><span class="time">08:00<small>PM</small></span><i class="line-dot"></i><p><b>Evening Smash</b><small>Right Court · 8/12 members</small></p><span class="status available">4 slots left</span></div></div></article>
        <article class="panel occupancy"><div class="panel-head"><div><h3>Court occupancy</h3><p>Current capacity overview</p></div><button class="dots"><i class="fa-solid fa-ellipsis"></i></button></div><div class="court-row"><span class="court-icon left"><i class="fa-solid fa-table-cells-large"></i></span><div><b>Left Court</b><p><span class="progress"><i style="width:75%"></i></span><small>27 of 36 slots occupied</small></p></div><strong>75%</strong></div><div class="court-row"><span class="court-icon right"><i class="fa-solid fa-table-cells-large"></i></span><div><b>Right Court</b><p><span class="progress purple-progress"><i style="width:64%"></i></span><small>23 of 36 slots occupied</small></p></div><strong>64%</strong></div></article>
      </div>
    </section>

    <section class="page" id="members"><div class="section-title"><div><p class="eyebrow">MEMBER DIRECTORY</p><h2>Members</h2><span>Manage academy memberships and assignments.</span></div><button class="primary-btn" data-modal="memberModal"><i class="fa-solid fa-plus"></i>Add member</button></div><div class="panel table-panel"><div class="table-controls"><label class="search"><i class="fa-solid fa-magnifying-glass"></i><input id="memberSearch" placeholder="Search name or phone..."></label><select id="batchFilter"><option value="">All batches</option><option>Morning Elite</option><option>Evening Smash</option><option>Weekend Warriors</option></select><select id="courtFilter"><option value="">All courts</option><option>Left Court</option><option>Right Court</option></select><select id="paymentFilter"><option value="">All payment status</option><option>Paid</option><option>Pending</option><option>Partially Paid</option></select><button class="outline-btn"><i class="fa-solid fa-arrow-down-wide-short"></i>Filters</button></div><div class="table-wrap"><table><thead><tr><th>MEMBER</th><th>BATCH / COURT</th><th>MONTHLY FEE</th><th>PAYMENT STATUS</th><th>LAST PAID</th><th>STATUS</th><th></th></tr></thead><tbody id="membersTable"></tbody></table></div><div class="table-footer"><span>Showing <b id="memberCount">6</b> of 128 members</span><div class="pager"><button disabled><i class="fa-solid fa-chevron-left"></i></button><button class="active-page">1</button><button>2</button><button>3</button><button><i class="fa-solid fa-chevron-right"></i></button></div></div></div></section>

    <section class="page" id="batches"><div class="section-title"><div><p class="eyebrow">FLEXIBLE SCHEDULING</p><h2>Batches & Timings</h2><span>Edit timing, capacity, court, and availability without changing code.</span></div><button class="primary-btn" data-modal="batchModal"><i class="fa-solid fa-plus"></i>Add batch</button></div><div class="batch-tabs"><button class="tab active">Weekdays</button><button class="tab">Weekend</button></div><div class="batch-cards" id="batchCards"></div></section>

    <section class="page" id="courts"><div class="section-title"><div><p class="eyebrow">COURT MANAGEMENT</p><h2>Courts</h2><span>Live utilization across the academy.</span></div></div><div class="court-management"><article class="court-card"><div class="court-banner blue-banner"><i class="fa-solid fa-table-cells-large"></i><span>LEFT COURT</span><b>75% occupied</b></div><div class="court-body"><h3>Left Court</h3><p>3 active batches · 27 active members</p><div class="court-stat"><span>Today's occupancy</span><b>3 / 4 slots</b></div><button class="outline-btn wide">View schedule</button></div></article><article class="court-card"><div class="court-banner purple-banner"><i class="fa-solid fa-table-cells-large"></i><span>RIGHT COURT</span><b>64% occupied</b></div><div class="court-body"><h3>Right Court</h3><p>3 active batches · 23 active members</p><div class="court-stat"><span>Today's occupancy</span><b>2 / 4 slots</b></div><button class="outline-btn wide">View schedule</button></div></article></div></section>

    <section class="page" id="payments"><div class="section-title"><div><p class="eyebrow">FINANCIALS</p><h2>Fees & Payments</h2><span>Track monthly fees, collections, and outstanding balances.</span></div><button class="primary-btn" data-modal="paymentModal"><i class="fa-solid fa-plus"></i>Record payment</button></div><div class="finance-summary"><article><span class="stat-icon mint"><i class="fa-solid fa-circle-check"></i></span><div><p>Fees paid</p><h3>₹1,08,500</h3><small>72 members paid in July</small></div></article><article><span class="stat-icon rose"><i class="fa-solid fa-hourglass-half"></i></span><div><p>Fees pending</p><h3>₹18,400</h3><small>6 members need follow-up</small></div></article><article><span class="stat-icon blue"><i class="fa-solid fa-money-bill-transfer"></i></span><div><p>Collection rate</p><h3>85.5%</h3><small>Up 4.2% from June</small></div></article></div><div class="panel table-panel"><div class="table-controls"><label class="search"><i class="fa-solid fa-magnifying-glass"></i><input placeholder="Search payment records..."></label><select><option>July 2026</option><option>June 2026</option></select><button class="outline-btn"><i class="fa-solid fa-file-export"></i>Export</button></div><div class="table-wrap"><table><thead><tr><th>MEMBER NAME</th><th>MONTH</th><th>AMOUNT</th><th>PAID DATE</th><th>MODE</th><th>STATUS</th><th>REFERENCE</th></tr></thead><tbody><tr><td><b>Arjun Kumar</b><small>SK-1024</small></td><td>July 2026</td><td><b>₹1,500</b></td><td>Jul 03, 2026</td><td><span class="mode"><i class="fa-solid fa-mobile-screen"></i>UPI</span></td><td><span class="status paid">Paid</span></td><td>UPI87302</td></tr><tr><td><b>Meera Iyer</b><small>SK-1041</small></td><td>July 2026</td><td><b>₹1,800</b></td><td>Jul 05, 2026</td><td><span class="mode"><i class="fa-solid fa-money-bill"></i>Cash</span></td><td><span class="status paid">Paid</span></td><td>—</td></tr><tr><td><b>Rahul Prakash</b><small>SK-1017</small></td><td>July 2026</td><td><b>₹750</b></td><td>Jul 12, 2026</td><td><span class="mode"><i class="fa-solid fa-building-columns"></i>Bank</span></td><td><span class="status partial">Partially paid</span></td><td>HDFC9210</td></tr></tbody></table></div></div></section>

    <section class="page" id="schedule"><div class="section-title"><div><p class="eyebrow">DAILY OPERATIONS</p><h2>Batch schedule</h2><span>Court × time view. Update any batch from Batches & Timings.</span></div><button class="outline-btn"><i class="fa-regular fa-calendar"></i>Weekdays <i class="fa-solid fa-chevron-down"></i></button></div><div class="schedule-legend"><span><i class="legend available-legend"></i>Available</span><span><i class="legend partial-legend"></i>Partially filled</span><span><i class="legend full-legend"></i>Full</span><span><i class="legend inactive-legend"></i>Inactive</span></div><div class="schedule-block"><h3><i class="fa-solid fa-sun"></i>Morning batches</h3><div class="schedule-table"><div class="schedule-head"><span>TIME</span><span>LEFT COURT</span><span>RIGHT COURT</span></div><div class="schedule-row"><span>6:00 – 7:00 AM</span><div class="slot partial-slot"><b>Morning Elite</b><small>10 / 12 members</small></div><div class="slot available-slot"><b>Open slot</b><small>Available for a new batch</small></div></div><div class="schedule-row"><span>7:00 – 8:00 AM</span><div class="slot available-slot"><b>Morning Rally</b><small>8 / 12 members</small></div><div class="slot full-slot"><b>Morning Power</b><small>12 / 12 members</small></div></div><div class="schedule-row"><span>8:00 – 9:00 AM</span><div class="slot inactive-slot"><b>No batch</b><small>Inactive</small></div><div class="slot partial-slot"><b>Morning Advance</b><small>9 / 12 members</small></div></div></div></div><div class="schedule-block"><h3><i class="fa-solid fa-moon"></i>Evening batches</h3><div class="schedule-table"><div class="schedule-head"><span>TIME</span><span>LEFT COURT</span><span>RIGHT COURT</span></div><div class="schedule-row"><span>8:00 – 9:00 PM</span><div class="slot available-slot"><b>Open slot</b><small>Available for a new batch</small></div><div class="slot partial-slot"><b>Evening Smash</b><small>8 / 12 members</small></div></div></div></div></section>

    <section class="page" id="reports"><div class="section-title"><div><p class="eyebrow">ACADEMY INSIGHTS</p><h2>Reports</h2><span>Download clean summaries for your records.</span></div><button class="primary-btn"><i class="fa-solid fa-file-excel"></i>Export all reports</button></div><div class="report-grid"><article><i class="fa-solid fa-chart-line"></i><h3>Monthly revenue</h3><p>Collection, targets and month-over-month growth.</p><button>View report <i class="fa-solid fa-arrow-right"></i></button></article><article><i class="fa-solid fa-user-clock"></i><h3>Pending fees</h3><p>Outstanding amounts grouped by member and batch.</p><button>View report <i class="fa-solid fa-arrow-right"></i></button></article><article><i class="fa-solid fa-table-cells-large"></i><h3>Court-wise members</h3><p>Active member allocation and court capacity.</p><button>View report <i class="fa-solid fa-arrow-right"></i></button></article><article><i class="fa-solid fa-credit-card"></i><h3>Payment modes</h3><p>Cash, UPI, bank transfer and other breakdown.</p><button>View report <i class="fa-solid fa-arrow-right"></i></button></article></div></section>

    <section class="page" id="data"><div class="section-title"><div><p class="eyebrow">EXCEL DATA WORKFLOW</p><h2>Excel / Data management</h2><span>Keep records portable and organized in familiar Excel sheets.</span></div></div><div class="data-grid"><article><div class="excel-icon"><i class="fa-solid fa-file-excel"></i></div><h3>Members sheet</h3><p>Member ID, contact, batch, court, timing, fee and status.</p><div><button class="primary-btn small">Import members</button><button class="outline-btn">Export</button></div></article><article><div class="excel-icon"><i class="fa-solid fa-file-excel"></i></div><h3>Payments sheet</h3><p>Payment ID, month, amount, mode, reference and remarks.</p><div><button class="primary-btn small">Import payments</button><button class="outline-btn">Export</button></div></article><article><div class="excel-icon"><i class="fa-solid fa-file-excel"></i></div><h3>Batches sheet</h3><p>Batch ID, day, session, time, court, capacity and status.</p><div><button class="primary-btn small">Import batches</button><button class="outline-btn">Export</button></div></article></div><div class="info-callout"><i class="fa-solid fa-circle-info"></i><p><b>Your records stay safe.</b> Imports are reviewed before updating the academy directory, so existing records are not overwritten accidentally.</p></div></section>
    <section class="page" id="settings"><div class="section-title"><div><p class="eyebrow">PREFERENCES</p><h2>Settings</h2><span>Academy basics and administration preferences.</span></div></div><div class="panel settings-panel"><h3>Academy profile</h3><div class="form-grid"><label>Academy name<input value="Super Kings Badminton Academy"></label><label>Contact number<input value="+91 98765 43210"></label><label>Default monthly fee<input value="₹1,500"></label><label>Timezone<select><option>Asia/Kolkata (IST)</option></select></label></div><button class="primary-btn">Save changes</button></div></section>
  </main>

  <div class="modal" id="memberModal"><div class="modal-card"><button class="close-modal"><i class="fa-solid fa-xmark"></i></button><p class="eyebrow">NEW REGISTRATION</p><h2>Add a new member</h2><form id="memberForm"><div class="form-grid"><label>Member name<input required id="newName" placeholder="Enter full name"></label><label>Phone number<input required placeholder="+91 00000 00000"></label><label>Batch<select id="newBatch"><option>Morning Elite</option><option>Evening Smash</option><option>Weekend Warriors</option></select></label><label>Court<select id="newCourt"><option>Left Court</option><option>Right Court</option></select></label><label>Monthly fee<input id="newFee" value="₹1,500"></label><label>Payment status<select id="newStatus"><option>Paid</option><option>Pending</option><option>Partially Paid</option></select></label></div><button class="primary-btn form-submit" type="submit">Add member</button></form></div></div>
  <div class="modal" id="batchModal"><div class="modal-card"><button class="close-modal"><i class="fa-solid fa-xmark"></i></button><p class="eyebrow">FLEXIBLE SCHEDULING</p><h2>Add batch timing</h2><form id="batchForm"><div class="form-grid"><label>Batch name<input id="newBatchName" required placeholder="e.g. Morning Champions"></label><label>Court<select id="batchCourt"><option>Left Court</option><option>Right Court</option></select></label><label>Start time<input type="time" id="startTime" required value="06:00"></label><label>End time<input type="time" id="endTime" required value="07:00"></label><label>Session<select><option>Morning</option><option>Evening</option></select></label><label>Capacity<input type="number" value="12"></label></div><button class="primary-btn form-submit" type="submit">Create batch</button></form></div></div>
  <div class="modal" id="editBatchModal"><div class="modal-card"><button class="close-modal"><i class="fa-solid fa-xmark"></i></button><p class="eyebrow">EDIT BATCH</p><h2>Update batch details</h2><form id="editBatchForm"><div class="form-grid"><label>Batch name<input id="editBatchName" required></label><label>Court<select id="editBatchCourt"><option>Left Court</option><option>Right Court</option></select></label><label>Start time<input type="time" id="editStartTime" required></label><label>End time<input type="time" id="editEndTime" required></label><label>Session<select id="editSession"><option>Morning</option><option>Evening</option></select></label><label>Capacity<input id="editCapacity" type="number" min="1" required></label><label>Status<select id="editBatchStatus"><option>Active</option><option>Inactive</option></select></label></div><button class="primary-btn form-submit" type="submit">Save batch changes</button></form></div></div>
  <div class="modal" id="feeModal"><div class="modal-card"><button class="close-modal"><i class="fa-solid fa-xmark"></i></button><p class="eyebrow">MEMBER & PARTNER FEES</p><h2>Update member details</h2><form id="feeForm"><p id="feeMemberName"></p><div class="form-grid"><label>Member name<input id="editMemberName" required></label><label>Member status<select id="editMemberStatus"><option>Active</option><option>Inactive</option></select></label><label>Owner 1 monthly amount<input id="ownerOneFee" required inputmode="numeric" placeholder="₹750"></label><label>Owner 1 payment status<select id="ownerOneStatus"><option>Paid</option><option>Pending</option><option>Partially Paid</option></select></label><label>Owner 2 monthly amount<input id="ownerTwoFee" required inputmode="numeric" placeholder="₹750"></label><label>Owner 2 payment status<select id="ownerTwoStatus"><option>Paid</option><option>Pending</option><option>Partially Paid</option></select></label><label>Last paid date<input id="editPaidDate" placeholder="e.g. Jul 30, 2026"></label></div><button class="primary-btn form-submit" type="submit">Save member changes</button><button class="delete-btn" id="deleteMemberButton" type="button"><i class="fa-solid fa-trash"></i> Delete member</button></form></div></div>
  <div class="modal" id="paymentModal"><div class="modal-card"><button class="close-modal"><i class="fa-solid fa-xmark"></i></button><p class="eyebrow">PAYMENT ENTRY</p><h2>Record payment</h2><form><div class="form-grid"><label>Member<select><option>Arjun Kumar</option><option>Rahul Prakash</option><option>Ananya Nair</option></select></label><label>Month<input value="July 2026"></label><label>Amount<input value="₹1,500"></label><label>Payment mode<select><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Other</option></select></label><label>Reference number<input placeholder="Optional"></label><label>Paid date<input type="date"></label></div><button class="primary-btn form-submit" type="button">Save payment</button></form></div></div>
  <script src="js/main.js"></script>
</body>
</html>
