const members=[
 {name:'Arjun Kumar',initials:'AK',color:'blue-avatar',id:'SK-1024',batch:'Morning Elite',court:'Left Court',fee:'₹1,500',payment:'Paid',paid:'Jul 03, 2026',status:'Active'},
 {name:'Meera Iyer',initials:'MI',color:'purple',id:'SK-1041',batch:'Evening Smash',court:'Right Court',fee:'₹1,800',payment:'Paid',paid:'Jul 05, 2026',status:'Active'},
 {name:'Rahul Prakash',initials:'RP',color:'coral',id:'SK-1017',batch:'Morning Elite',court:'Left Court',fee:'₹1,500',payment:'Partially Paid',paid:'Jul 12, 2026',status:'Active'},
 {name:'Ananya Nair',initials:'AN',color:'amber',id:'SK-1033',batch:'Evening Smash',court:'Right Court',fee:'₹1,800',payment:'Pending',paid:'Jun 08, 2026',status:'Active'},
 {name:'Vikram Shah',initials:'VS',color:'purple',id:'SK-1008',batch:'Morning Elite',court:'Left Court',fee:'₹1,500',payment:'Pending',paid:'Jun 04, 2026',status:'Active'},
 {name:'Sneha Menon',initials:'SM',color:'blue-avatar',id:'SK-1052',batch:'Weekend Warriors',court:'Right Court',fee:'₹1,800',payment:'Pending',paid:'Jun 10, 2026',status:'Inactive'}];
const batches=[
 {name:'Morning Elite',start:'06:00',end:'07:00',court:'Left Court',session:'Morning',capacity:12,filled:10,status:'Active',weekend:false},
 {name:'Morning Rally',start:'07:00',end:'08:00',court:'Right Court',session:'Morning',capacity:12,filled:12,status:'Active',weekend:false},
 {name:'Morning Advance',start:'08:00',end:'09:00',court:'Right Court',session:'Morning',capacity:12,filled:9,status:'Active',weekend:false},
 {name:'Evening Smash',start:'20:00',end:'21:00',court:'Right Court',session:'Evening',capacity:12,filled:8,status:'Active',weekend:false},
 {name:'Weekend Warriors',start:'07:00',end:'08:30',court:'Right Court',session:'Morning',capacity:12,filled:8,status:'Active',weekend:true}];
let editingBatch=-1,editingMember=-1,currentBatchView='weekday';
const timeLabel=t=>{let[h,m]=t.split(':').map(Number);const suffix=h>=12?'PM':'AM';return `${h%12||12}:${String(m).padStart(2,'0')} ${suffix}`};
const statusClass=s=>s==='Paid'?'paid':s==='Pending'?'full':'partial';
const amount=value=>Number(String(value).replace(/[^0-9.]/g,''))||0;
const money=value=>'₹'+Number(value).toLocaleString('en-IN');
members.forEach(member=>{const half=amount(member.fee)/2;member.ownerOne=half;member.ownerTwo=half;member.ownerOneStatus=member.payment;member.ownerTwoStatus=member.payment});
const closeModal=m=>m.classList.remove('show');
function renderMembers(){const q=document.querySelector('#memberSearch')?.value.toLowerCase()||'',batch=document.querySelector('#batchFilter')?.value||'',court=document.querySelector('#courtFilter')?.value||'',payment=document.querySelector('#paymentFilter')?.value||'';const list=members.filter(m=>(m.name.toLowerCase().includes(q)||m.id.toLowerCase().includes(q))&&(!batch||m.batch===batch)&&(!court||m.court===court)&&(!payment||m.payment===payment));const body=document.querySelector('#membersTable');if(!body)return;body.innerHTML=list.map(m=>{const index=members.indexOf(m);m.fee=money(m.ownerOne+m.ownerTwo);return `<tr><td><div class="member-cell"><span class="avatar ${m.color}">${m.initials}</span><span><b>${m.name}</b><small>${m.id}</small></span></div></td><td><b>${m.batch}</b><small>${m.court}</small></td><td><b>${m.fee}</b><small>O1: ${money(m.ownerOne)} · O2: ${money(m.ownerTwo)}</small></td><td><span class="status ${statusClass(m.payment)}">${m.payment}</span></td><td>${m.paid}</td><td><span class="status ${m.status==='Active'?'paid':'inactive-slot'}">${m.status}</span></td><td><button class="edit-member dots" data-member="${index}" title="Edit member"><i class="fa-solid fa-pen"></i></button></td></tr>`}).join('');document.querySelector('#memberCount').textContent=list.length;document.querySelectorAll('.edit-member').forEach(button=>button.addEventListener('click',()=>openFeeEditor(Number(button.dataset.member))));}
function renderBatches(){const wrap=document.querySelector('#batchCards');if(!wrap)return;const weekend=currentBatchView==='weekend';const list=batches.filter(b=>b.weekend===weekend);wrap.innerHTML=list.map(b=>{const index=batches.indexOf(b);return `<article class="batch-card"><button class="edit-batch" data-batch="${index}" title="Edit batch"><i class="fa-solid fa-pen"></i></button><span class="status ${b.status==='Active'?'paid':'inactive-slot'}">${b.status}</span><h3>${b.name}</h3><p>${weekend?'Weekend ':''}${b.session} session</p><div class="batch-time"><i class="fa-regular fa-clock"></i>${timeLabel(b.start)} – ${timeLabel(b.end)}</div><div class="batch-meta"><span><i class="fa-solid fa-table-cells-large"></i> ${b.court}</span><span><i class="fa-solid fa-users"></i> ${b.filled} / ${b.capacity} members</span></div></article>`}).join('')||'<p class="muted">No batches have been added for this view yet.</p>';document.querySelectorAll('.edit-batch').forEach(button=>button.addEventListener('click',()=>openBatchEditor(Number(button.dataset.batch))));}
function openBatchEditor(index){const b=batches[index];editingBatch=index;document.querySelector('#editBatchName').value=b.name;document.querySelector('#editBatchCourt').value=b.court;document.querySelector('#editStartTime').value=b.start;document.querySelector('#editEndTime').value=b.end;document.querySelector('#editSession').value=b.session;document.querySelector('#editCapacity').value=b.capacity;document.querySelector('#editBatchStatus').value=b.status;document.querySelector('#editBatchModal').classList.add('show');}
function openFeeEditor(index){const m=members[index];editingMember=index;document.querySelector('#feeMemberName').textContent=`${m.name} (${m.id})`;document.querySelector('#editMemberName').value=m.name;document.querySelector('#ownerOneFee').value=money(m.ownerOne);document.querySelector('#ownerTwoFee').value=money(m.ownerTwo);document.querySelector('#ownerOneStatus').value=m.ownerOneStatus;document.querySelector('#ownerTwoStatus').value=m.ownerTwoStatus;document.querySelector('#editPaidDate').value=m.paid==='—'?'':m.paid;document.querySelector('#editMemberStatus').value=m.status;document.querySelector('#feeModal').classList.add('show');}
function showPage(page,label){document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelector('#pageTitle').innerHTML=page==='dashboard'?'Good morning, Admin <span>👋</span>':label;document.querySelector('#pageEyebrow').textContent=page==='dashboard'?'Overview':'Academy administration';document.querySelector('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();showPage(link.dataset.page,link.textContent.trim())}));
document.querySelectorAll('a[href="#payments"],a[href="#schedule"]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const page=link.getAttribute('href').slice(1);showPage(page,document.querySelector(`.nav-link[data-page="${page}"]`).textContent.trim())}));
document.querySelectorAll('[data-modal]').forEach(button=>button.addEventListener('click',()=>document.querySelector('#'+button.dataset.modal).classList.add('show')));document.querySelectorAll('.close-modal').forEach(button=>button.addEventListener('click',()=>closeModal(button.closest('.modal'))));document.querySelectorAll('.modal').forEach(modal=>modal.addEventListener('click',e=>{if(e.target===modal)closeModal(modal)}));
document.querySelector('#menuToggle').addEventListener('click',()=>document.querySelector('#sidebar').classList.toggle('open'));['memberSearch','batchFilter','courtFilter','paymentFilter'].forEach(id=>document.querySelector('#'+id)?.addEventListener('input',renderMembers));
document.querySelector('#memberForm').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#newName').value,monthly=amount(document.querySelector('#newFee').value),payment=document.querySelector('#newStatus').value;members.unshift({name,initials:name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(),color:'blue-avatar',id:'SK-'+(1060+members.length),batch:document.querySelector('#newBatch').value,court:document.querySelector('#newCourt').value,fee:money(monthly),ownerOne:monthly/2,ownerTwo:monthly/2,ownerOneStatus:payment,ownerTwoStatus:payment,payment,paid:'—',status:'Active'});renderMembers();closeModal(e.target.closest('.modal'));e.target.reset()});
document.querySelector('#batchForm').addEventListener('submit',e=>{e.preventDefault();batches.push({name:document.querySelector('#newBatchName').value,start:document.querySelector('#startTime').value,end:document.querySelector('#endTime').value,court:document.querySelector('#batchCourt').value,session:e.target.querySelector('select:not(#batchCourt)').value,capacity:Number(e.target.querySelector('input[type="number"]').value),filled:0,status:'Active',weekend:currentBatchView==='weekend'});renderBatches();closeModal(e.target.closest('.modal'));e.target.reset()});
document.querySelector('#editBatchForm').addEventListener('submit',e=>{e.preventDefault();const b=batches[editingBatch];b.name=document.querySelector('#editBatchName').value;b.court=document.querySelector('#editBatchCourt').value;b.start=document.querySelector('#editStartTime').value;b.end=document.querySelector('#editEndTime').value;b.session=document.querySelector('#editSession').value;b.capacity=Number(document.querySelector('#editCapacity').value);b.status=document.querySelector('#editBatchStatus').value;b.filled=Math.min(b.filled,b.capacity);renderBatches();closeModal(e.target.closest('.modal'))});
document.querySelector('#feeForm').addEventListener('submit',e=>{e.preventDefault();const m=members[editingMember];m.name=document.querySelector('#editMemberName').value;m.initials=m.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();m.ownerOne=amount(document.querySelector('#ownerOneFee').value);m.ownerTwo=amount(document.querySelector('#ownerTwoFee').value);m.ownerOneStatus=document.querySelector('#ownerOneStatus').value;m.ownerTwoStatus=document.querySelector('#ownerTwoStatus').value;m.payment=m.ownerOneStatus==='Paid'&&m.ownerTwoStatus==='Paid'?'Paid':m.ownerOneStatus==='Pending'&&m.ownerTwoStatus==='Pending'?'Pending':'Partially Paid';m.paid=document.querySelector('#editPaidDate').value||'—';m.status=document.querySelector('#editMemberStatus').value;renderMembers();closeModal(e.target.closest('.modal'))});
document.querySelector('#deleteMemberButton').addEventListener('click',()=>{const member=members[editingMember];if(confirm(`Delete ${member.name}? This cannot be undone.`)){members.splice(editingMember,1);renderMembers();closeModal(document.querySelector('#feeModal'))}});
document.querySelector('#editBatchForm').insertAdjacentHTML('beforeend','<button class="delete-btn" id="deleteBatchButton" type="button"><i class="fa-solid fa-trash"></i> Delete batch</button>');
document.querySelector('#deleteBatchButton').addEventListener('click',()=>{const batch=batches[editingBatch];if(confirm(`Delete ${batch.name}? This cannot be undone.`)){batches.splice(editingBatch,1);renderBatches();closeModal(document.querySelector('#editBatchModal'))}});
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');currentBatchView=tab.textContent.trim()==='Weekend'?'weekend':'weekday';renderBatches()}));
renderMembers();renderBatches();
